server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: node1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverUrl:
      defaultZone: http://node2:8762/eureka