server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: node2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverUrl:
      defaultZone: http://node1:8761/eureka